import type { GameStatus } from '../types/game';

export const STATUS_LIST: { value: GameStatus; label: string }[] = [
    { value: 'Wishlist', label: 'Wishlist' },
    { value: 'Queue', label: 'Queue' },
    { value: 'Playing', label: 'Playing' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Dropped', label: 'Dropped' },
];

export const PLATFORM_LIST = [
    'PC',
    'PlayStation 5',
    'Xbox One',
    'PlayStation 4',
    'Xbox Series S/X',
    'Nintendo Switch',
    'iOS',
    'Android',
    'Nintendo 3DS',
    'Nintendo DS',
    'Nintendo DSi',
    'macOS',
    'Linux',
    'Xbox 360',
    'Xbox',
    'PlayStation 3',
    'PlayStation 2',
    'PlayStation',
    'PS Vita',
    'PSP',
    'Wii U',
    'Wii',
    'GameCube',
    'Nintendo 64',
    'Game Boy Advance',
    'Game Boy Color',
    'Game Boy',
    'SNES',
    'NES',
    'Classic Macintosh',
    'Apple II',
    'Commodore / Amiga',
    'Atari 7800',
    'Atari 5200',
    'Atari 2600',
    'Atari Flashback',
    'Atari 8-bit',
    'Atari ST',
    'Atari Lynx',
    'Atari XEGS',
    'Genesis',
    'SEGA Saturn',
    'SEGA CD',
    'SEGA 32X',
    'SEGA Master System',
    'Dreamcast',
    '3DO',
    'Jaguar',
    'GameGear',
    'Neo Geo',
    'Web',
    'Retro',
    'Other'
];